### ISSUE TITLE
Windows on arm64

### ISSUE THREAD

**Issue by gedw99** [pojntfx/hydrapp#2]
I have windows on ARM64, so can test if you pump out a release for that.

**Comment by gedw99** [comment]
you already have it in the GitHub releases - my mistake

It's not on the Web page. thats why I missed it.

**Comment by pojntfx** [comment]
Sorry about that, yeah it's not in the MSI version because I can't cross-build CGo for it yet!

**Comment by gedw99** [comment]
What’s the cgo blocker ?  DB ?

**Comment by pojntfx** [comment]
Not quite - I just haven't set up WINE on ARM64 yet, and I'm not sure how cross-compilation would work for that platform tbh!

**Comment by gedw99** [comment]
this is for GitHub CI ?
